#  Laboratorio 2 - Python
## @author: Roberto Mendoza 

- <a href='#1.0'> 1.0 If statement </a> 
- <a href='#1.1'> 1.1 Nested if statement   </a> 
- <a href='#1.2'> 1.2 While   </a> 
- <a href='#1.3'> 1.3 For Loop  </a> 
- <a href='#1.4'> 1.4 Try and error </a> 
- <a href='#1.5'> 1.5 Function   </a> 

In [30]:
import random
import numpy as np
import math
import pandas as pd  # cargamos pandas (modulo que nos permitirá manipular bases de datos)
from tqdm import tqdm # hacer seguimeinto al loop (progreso)

## <a id='1.0'> 1.0 If statement </a> 

In [38]:
y = np.random.randint(-10, 10, 50)   # valores entre -10 y 10. Extraer 50 numeros. 

if np.mean(y) > 0 :
    dummy = 1
else :
    dummy = 0
        
print(dummy)

1


In [48]:
# short ifelse

dummy = 1 if np.mean(y) > 0 else  0

print(dummy)

1


## <a id='1.1'> 1.1 Nested if statement </a> 

In [66]:
v = 2
# v = np.nan
#v = "String"
#v = False

if isinstance( v, int ):
    print(v, " es numero entero (no missing)")
elif isinstance( v, str ):
    print(v, " es un string") 
elif isinstance( v, bool ):
    print(v, " es un logical")     
else:
    print("Sin resultado")        

2  es numero entero (no missing)


## <a id='1.2'> 1.2 While </a> 

In [68]:
# while without ending, the condition is always met

i = 0

while i < 10:
    print(i+1)

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


KeyboardInterrupt: 

In [70]:
# while requires a counter (i = i + 1)

i = 0

while i < 10:
    i = i + 1
    print(i)

1
2
3
4
5
6
7
8
9
10


### Si hoy tengo mis ahorros de S/.1,000.00. ¿Cuánto valdrán mis ahorros en 10 años a una tasa de interés de 5%?

$$
    S_{y+1}	=S_{y}(1+i)
$$

In [71]:
#  save
S = 1000

# Periods
n = 5

# interes rate
i = 0.05

In [72]:
year = 1
while year < n:
    S =  S * (1+i)
    year += 1
    print( year, S)

2 1050.0
3 1102.5
4 1157.625
5 1215.5062500000001


## <a id='1.3'> 1.3 For Loop </a> 

In [79]:
#### For Loop ##

ages = np.arange(1,100)

for age in ages:

    print(age+10 )  

11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109


In [80]:
np.arange(1,10000)

array([   1,    2,    3, ..., 9997, 9998, 9999])

In [81]:
len(ages)

99

In [78]:
y = np.zeros(len(ages))
y

array([0., 0., 0., ..., 0., 0., 0.])

In [83]:
y = np.zeros(len(ages)) # vector fills with 0

for i in range(len(ages)):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98


In [84]:
y = np.zeros(len(ages)) # vector fills with 0

for i in range(len(ages)):
    y[i] = np.log(ages[i])

In [85]:
y

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
       3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806,
       3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945,
       3.71357207, 3.73766962, 3.76120012, 3.78418963, 3.80666249,
       3.8286414 , 3.8501476 , 3.87120101, 3.8918203 , 3.91202301,
       3.93182563, 3.95124372, 3.97029191, 3.98898405, 4.00733319,
       4.02535169, 4.04305127, 4.06044301, 4.07753744, 4.09434456,
       4.11087386, 4.12713439, 4.14313473, 4.15888308, 4.17438727,
       4.18965474, 4.20469262, 4.21950771, 4.2341065 , 4.24849524,
       4.26267988, 4.27666612, 4.29045944, 4.30406509, 4.31748

In [87]:
# tqdm permite evaluar el progreso del loop

for i in tqdm(range(len(ages))):
    y[i] = np.log(ages[i])
    print(i)
    

100%|██████████████████████████████████████████████████████████████████████████████| 99/99 [00:00<00:00, 32486.00it/s]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98


In [14]:
y = np.log(ages)
y


array([0.        , 0.69314718, 1.09861229, ..., 9.21004033, 9.21014035,
       9.21024037])

In [89]:
# For + continue

for i in range(50):
    if i in range(15,21) :
        continue
        print(i)
   
    print("Ejecutanto",i,"\n")
        
        
# For + break

for i in range(50):
    if i in range(15,21) :
        break
    
    print("Ejecutanto",i,"\n")
             

Ejecutanto 0 

Ejecutanto 1 

Ejecutanto 2 

Ejecutanto 3 

Ejecutanto 4 

Ejecutanto 5 

Ejecutanto 6 

Ejecutanto 7 

Ejecutanto 8 

Ejecutanto 9 

Ejecutanto 10 

Ejecutanto 11 

Ejecutanto 12 

Ejecutanto 13 

Ejecutanto 14 

Ejecutanto 21 

Ejecutanto 22 

Ejecutanto 23 

Ejecutanto 24 

Ejecutanto 25 

Ejecutanto 26 

Ejecutanto 27 

Ejecutanto 28 

Ejecutanto 29 

Ejecutanto 30 

Ejecutanto 31 

Ejecutanto 32 

Ejecutanto 33 

Ejecutanto 34 

Ejecutanto 35 

Ejecutanto 36 

Ejecutanto 37 

Ejecutanto 38 

Ejecutanto 39 

Ejecutanto 40 

Ejecutanto 41 

Ejecutanto 42 

Ejecutanto 43 

Ejecutanto 44 

Ejecutanto 45 

Ejecutanto 46 

Ejecutanto 47 

Ejecutanto 48 

Ejecutanto 49 

Ejecutanto 0 

Ejecutanto 1 

Ejecutanto 2 

Ejecutanto 3 

Ejecutanto 4 

Ejecutanto 5 

Ejecutanto 6 

Ejecutanto 7 

Ejecutanto 8 

Ejecutanto 9 

Ejecutanto 10 

Ejecutanto 11 

Ejecutanto 12 

Ejecutanto 13 

Ejecutanto 14 



In [91]:
# For + none

for i in range(50):
    if i in range(15,21) :
        None
       
        
    print("Ejecutanto",i,"\n")
        

Ejecutanto 0 

Ejecutanto 1 

Ejecutanto 2 

Ejecutanto 3 

Ejecutanto 4 

Ejecutanto 5 

Ejecutanto 6 

Ejecutanto 7 

Ejecutanto 8 

Ejecutanto 9 

Ejecutanto 10 

Ejecutanto 11 

Ejecutanto 12 

Ejecutanto 13 

Ejecutanto 14 

Ejecutanto 15 

Ejecutanto 16 

Ejecutanto 17 

Ejecutanto 18 

Ejecutanto 19 

Ejecutanto 20 

Ejecutanto 21 

Ejecutanto 22 

Ejecutanto 23 

Ejecutanto 24 

Ejecutanto 25 

Ejecutanto 26 

Ejecutanto 27 

Ejecutanto 28 

Ejecutanto 29 

Ejecutanto 30 

Ejecutanto 31 

Ejecutanto 32 

Ejecutanto 33 

Ejecutanto 34 

Ejecutanto 35 

Ejecutanto 36 

Ejecutanto 37 

Ejecutanto 38 

Ejecutanto 39 

Ejecutanto 40 

Ejecutanto 41 

Ejecutanto 42 

Ejecutanto 43 

Ejecutanto 44 

Ejecutanto 45 

Ejecutanto 46 

Ejecutanto 47 

Ejecutanto 48 

Ejecutanto 49 



In [17]:
# Example 2

for j in range(101):
    print(j)
    if j > 20:
        break
    
#### While + break

w = 10

while True :
    coin = round( np.random.uniform(0,1) ) # redondear al entero más cercano
    if coin == 1 :
        break   # sale del while
    else:
        w = w + 10  # se ejecuta si el coin es igual a cero 
        print(coin)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
0
0


## <a id='1.4'> 1.4 Try and error </a> 

In [93]:
a = "2"
print(a/7)

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [94]:
a = "2"

try:     
    
    print(a/7)   # No corre el código si detecta un error 
    
except TypeError:
          None
    
# caso 2

try:
    
    print(a/7)
    
except Exception:
    
    print(int(a))

# caso 3}

try:
    
    print(a/7)

except Exception:
    
    print(int(a)/7)

finally:
    
    print("Siempre se ejecuta")

2
0.2857142857142857
Siempre se ejecuta


## <a id='1.5'> 1.5 Function </a> 

In [19]:
def calculator(x,y,z):
    result = x*y + z
    
    return result

print( calculator( 158, 38, 10 ) )

calculator( 158, 38)

6014


TypeError: calculator() missing 1 required positional argument: 'z'

In [20]:
# Different arguments location

print( calculator( z = 158, x = 38, y = 10 ) )


538


In [21]:
## return multiple

def calculator_square( x, y ):
    
    x2 = x * x
    y2 = y * y
    
    result = x2 * y2   
    
    return (result, x2, f"La multiplicación del cuadrado es: {result}")  # multiple resultado 

calculator_square(3, 4)
                  
print( calculator_square(3, 4)[1] )
calculator_square(3, 4)[2]
                

#### IF statement and return 
def calculator_square_2( x, y ):
    
    x2 = x * x
    y2 = y * y
    
    result = x2 * y2  
    
    if result <= 200:
           return f"Large number. Get only the result variable {result}"
    else:
           return  print( "Too large number. Do not return variables!")


calculator_square_2(300, 4)


## Función y tipo de variables


def calculator_base_5( x , y = 5 ):
    
    result = x * y
    
    return result


calculator_base_5( 7 )

9
Too large number. Do not return variables!


35

### Si hoy tengo mis ahorros de S/.1,000.00. ¿Cuánto valdrán mis ahorros en 10 años a una tasa de interés de 5%?

$$
    S_{t}	=S_{o}(1+i)^t
$$

### Ejemplo en finanzas

In [22]:
portfolio = pd.read_csv(r'../../data/Portafolio.csv')

In [23]:
print(portfolio.shape)
portfolio.head()

(100, 2)


X         Y
0 -0.895251 -0.234924
1 -1.562454 -0.885176
2 -0.417090  0.271888
3  1.044356 -0.734198
4 -0.315568  0.841983

In [24]:
X = portfolio['X']
y = portfolio['Y']

In [25]:
np.cov(X,y)

array([[1.12864236, 0.62635829],
       [0.62635829, 1.30823747]])

In [26]:
def alpha(data):
    X = data['X']
    y = data['Y']
    
    cal_alpha = (np.var(y, ddof=1) - np.cov(X,y)[0][1]) / (np.var(X, ddof=1) + np.var(y, ddof=1) - 2*(np.cov(X,y)[0][1]))
    
    return cal_alpha

In [27]:
# "\" consecutive line codes 

def alpha(data):
    X = data['X']
    y = data['Y']
    
    cal_alpha = (np.var(y, ddof=1) - np.cov(X,y)[0][1])\
    / (np.var(X, ddof=1) + np.var(y, ddof=1) - 2*(np.cov(X,y)[0][1]))
    
    return cal_alpha

In [28]:
alpha(portfolio)

0.57583207459283

In [3]:
a = 1200
b=0.01
c=7

monto_in=a
interes=b
num_perid=c

monto_fi= a*(1+b)**c
interes_2=monto_fi-monto_in

print("El monto final será",monto_fi,"y el interés ganado será")

El monto final será 1286.562422528412 y el interés ganado será
